package CSGFramework.Generator;

import CSGFramework.User.User;
import CSGFramework.User.UserBuilder;
import CSGFramework.Website.Website;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.EnumSet;
import java.util.List;

/**
 * Class
 */
public class ClickStreamGeneratorBuilder {
    private Website website;
    private int numberOfAutoGeneratedUsers = 20;
    private List<User> users = generateUsers();
    private int numberOfLinesToGenerate = 100;
    //TODO: This list should contain values from AvailableOptions enum
    private List<AvailableOptions> includeInGeneratedData = new ArrayList<>(Arrays.asList(AvailableOptions.class.getEnumConstants()));//new ArrayList<>(Arrays.asList("userId", "ationId", "urlOfPageActionWasPerformedOn", "timeActionWasPerformed"));


    public ClickStreamGeneratorBuilder setWebsite(Website website) {
        this.website = website;
        return this;
    }

    public ClickStreamGeneratorBuilder setNumberOfAutoGeneratedUsers(int numberOfAutoGeneratedUsers){
        this.numberOfAutoGeneratedUsers = numberOfAutoGeneratedUsers;
        return this;
    }

    public ClickStreamGeneratorBuilder addUsers(List<User> users) {
        this.users.addAll(users);
        return this;
    }

    public ClickStreamGeneratorBuilder addUser(User user) {
        this.users.add(user);
        return this;
    }

    public ClickStreamGeneratorBuilder setNumberOfLinesToGenerate(int numberOfLinesToGenerate) {
        this.numberOfLinesToGenerate = numberOfLinesToGenerate;
        return this;
    }


    public ClickStreamGeneratorBuilder includeIpAdress(){
        //TODO: create multiple include...() methods, so the user can choose to include non-defauld columns
        // in the data that is generated
        return this;
    }

    public ClickStreamGeneratorBuilder excludeDate(){
        //TODO: Create multiple exlude...() methods, so the user can choose to exclude columns
        // in the data that is generated
        includeInGeneratedData.remove(AvailableOptions.timeActionWasPerformed);
        return this;
    }

    public ClickStreamGenerator build(){
        System.out.println(includeInGeneratedData);

        return new ClickStreamGenerator(website,users,numberOfLinesToGenerate);
    }


    /////////////////////////////////////// PRIVATE: ONLY USED BY FRAMEWORK /////////////////////////////////////////////////

    /**
     * Method that genereates a set of default users
     * @return a List of users
     */
    private ArrayList<User> generateUsers(){
        ArrayList<User> returnList = new ArrayList<>();
        for (int i = 1; i <= numberOfAutoGeneratedUsers; i++){
            returnList.add(new UserBuilder().setId("User" + i).build());
        }
        return returnList;
    }
}
