package CSGFramework.Generator;

import CSGFramework.User.User;
import CSGFramework.User.UserBuilder;
import CSGFramework.Website.Website;
import CSGFramework.Website.WebsiteBuilder;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Class
 */
public class ClickStreamGeneratorBuilder {
    private Website website = new WebsiteBuilder().build();
    private int numberOfAutoGeneratedUsers = 10;
    private List<User> users = new ArrayList<>();
    private int numberOfLinesToGenerate = 100;
    //TODO: This list should contain values from AvailableOptions enum
    private List<AvailableOptions> includedDataFields = new ArrayList<>(Arrays.asList(AvailableOptions.class.getEnumConstants()));//new ArrayList<>(Arrays.asList("userId", "ationId", "urlOfPageActionWasPerformedOn", "timeActionWasPerformed"));


    public ClickStreamGeneratorBuilder setWebsite(Website website) {
        this.website = website;
        return this;
    }

    public ClickStreamGeneratorBuilder setNumberOfAutoGeneratedUsers(int numberOfAutoGeneratedUsers){
        this.numberOfAutoGeneratedUsers = numberOfAutoGeneratedUsers;
        System.out.println(this.numberOfAutoGeneratedUsers);
        return this;
    }

    public ClickStreamGeneratorBuilder addUsers(List<User> users) {
        //TODO: Set current viewing page to homePage
        this.users.addAll(users);
        return this;
    }

    public ClickStreamGeneratorBuilder addUser(User user) {
        //TODO: Set current viewing page to homePage
        this.users.add(user);
        return this;
    }

    public ClickStreamGeneratorBuilder setNumberOfLinesToGenerate(int numberOfLinesToGenerate) {
        this.numberOfLinesToGenerate = numberOfLinesToGenerate;
        return this;
    }


    public ClickStreamGeneratorBuilder includeIpAdress(){
        //TODO: create multiple include...() methods, so the user can choose to include non-defauld columns
        // in the data that is generated
        return this;
    }

    public ClickStreamGeneratorBuilder excludeDate(){
        //TODO: Create multiple exlude...() methods, so the user can choose to exclude columns
        // in the data that is generated
        includedDataFields.remove(AvailableOptions.timeActionWasPerformed);
        return this;
    }

    /**
     * The build function will first check if any users exist, if not generate 10 or an specified amount, before returning a generator.
     * @return Object of the generator
     */
    public ClickStreamGenerator build(){
        if (users.isEmpty()){
            generateUsers(numberOfAutoGeneratedUsers);
        }
        return new ClickStreamGenerator(website,users,numberOfLinesToGenerate);
    }


    /////////////////////////////////////// PRIVATE: ONLY USED BY FRAMEWORK /////////////////////////////////////////////////

    /**
     * Method that genereates a set of default users and sets the current viewing page to homePage
     * @return a List of users
     */
    private ClickStreamGeneratorBuilder generateUsers(int numberOfAutoGeneratedUsers){
        ArrayList<User> returnList = new ArrayList<>();
        for (int i = 1; i <= numberOfAutoGeneratedUsers; i++){
            returnList.add(new UserBuilder().setId("User" + i).setCurrentViewingWebpage(website.getHomeWebpage()).build());
        }
        System.out.println(returnList);
        users.addAll(returnList);
        return this;
    }
}
