package CSGFramework.Website;

import java.util.*;

import static java.lang.Thread.sleep;

public class WebpageBuilder {
    // A site that the page belongs to
    private final static Website defaultWebsite = new WebsiteBuilder().build();
    private Website website = defaultWebsite;
    private String url;
    private int numberOfAutogeneratedActions = 5;
    HashMap<Action, Webpage> possibleActions = new HashMap<>();

    /**
     * Method that
     * @param numberOfAutogeneratedActions
     * @return an instance of WebpageBuilder with number of autogenerated actions set
     */
    public WebpageBuilder setNumberOfAutogeneratedActions(int numberOfAutogeneratedActions) {
        this.numberOfAutogeneratedActions = numberOfAutogeneratedActions;
        return this;
    }


    /**
     *
     * @param url String URL of the Webpage
     * @return an instance of WebpageBuilder with the URL set
     */
    public WebpageBuilder setUrl(String url) {
        this.url = url;
        return this;
    }

    public WebpageBuilder setWebsite(Website website) {
        this.website = website;
        return this;
    }


    public WebpageBuilder addNonRedirectingeAction(Action action){
        possibleActions.put(action,null);
        return this;
    }

    public WebpageBuilder addNonRedirectingeActions(List<Action> actionsToAdd){
        for (Action action: actionsToAdd) {
            possibleActions.put(action,null);
        }
        return this;
    }

    /**
     * Method that ads one redirecting action to the web page
     * @param action action that user wants to add
     * @param webpage @Nullable webpage that action redirects to
     * @return object if WebpageBuilder
     */
    public WebpageBuilder addRedirectingAction(Action action, Webpage webpage){
        possibleActions.put(action, webpage);
        return this;
    }

    /**
     * Method that adds multiple redirecting actions to this web page
     * @param actionsToAdd
     * @return
     */
    public WebpageBuilder addRedirectingActions(HashMap<Action, Webpage> actionsToAdd){
        possibleActions.putAll(actionsToAdd);
        return this;
    }

    /**
     * Method that builds an object of a web page with the applied values
     * Checks if the list of possible actions for the page is empty and if the number of autogenerated actions is set
     * if so, it generates a number of non redirecting actions
     * @return an object of a Webpage
     */
    public Webpage build(){
        if(possibleActions.isEmpty() && numberOfAutogeneratedActions >0){
            generateRedirectingActions(numberOfAutogeneratedActions);
        }
        return new Webpage(url,possibleActions);
    }

    // UPDATED before final
    /**
     * Method that creates redirecting actions, it will try to redirect to pages on the website,
     * but if there are not enough pages or page(i) is this page, it will redirect to a random page.
     * @param numberOfRedirectingActions takes number of redirecting actions user wants to create
     * @param website the website actions belong to
     * @return returns an opbject of the builder
     */
    public WebpageBuilder generateRedirectingActions(int numberOfRedirectingActions, Website website){
        HashMap<Action, Webpage> returnMap = new HashMap<>();
        List<Webpage> webpages = website.getAllWebpages();
        /*
        // the method has to generate numberOfRedirecting actions but generates the max(numberOfRedirectingActions, webpages.size)
        int numberOfActions = Math.max(webpages.size(),numberOfRedirectingActions);
        System.out.println(numberOfActions + "!!!!!!!!!!");
        for (int i = 0; i < numberOfActions; i++){
            returnMap.put(new ActionBuilder().setActionId("RedAction" + i).build(), webpages.get(i));
        }
        */
        for (int i =0; i < numberOfRedirectingActions; i++){
            if (i > webpages.size() - 1){
                returnMap.put(new ActionBuilder().build(),new WebpageBuilder().setUrl("randompage" + i +".com").build());
            }
            //TODO: This is redundant? since method is called in builder, this page will newer be a part of the website before we add it.
            else if(webpages.get(i).getUrl() == this.url){
                returnMap.put(new ActionBuilder().build(),new WebpageBuilder().setUrl("randompage" + i +".com").build());
            }
            else{
                returnMap.put(new ActionBuilder().build(),webpages.get(i));
            }
        }
        possibleActions.putAll(returnMap);
        System.out.println(possibleActions);
        return this;
    }

    // Created before final
    /**
     * Overriding method: This one does not take a website as a param, and will only redirect to external websites.
     * Should only be used on single page websites!
     * @param numberOfRedirectingActions the number of actions to generate
     * @return an instance of the builder
     */
    public WebpageBuilder generateRedirectingActions(int numberOfRedirectingActions){
        //HashMap<Action, Webpage> returnMap = new HashMap<>();
        for(int i = 0; i < numberOfRedirectingActions; i++){
            Action action = new ActionBuilder().build();
            possibleActions.put(action,new WebpageBuilder().setUrl("randompage" + i +".com").setNumberOfAutogeneratedActions(0).build());
        }
        //possibleActions.putAll(returnMap);
        return this;
    }

    /**
     * Method that generates non redirecting actions
     * @param a is the number of redirecting action generated for this webpage
     * @return returns an instance of the WebpageBuilder
     */
    public WebpageBuilder generateNonRedirectingActions(int a){
        HashMap<Action, Webpage> returnMap = new HashMap<>();
        for(int i = 0; i < a; i ++){
            Action action = new ActionBuilder().build();
            returnMap.put(action,null);
        }

        // How To iterate through a hashmap
        /*
        Iterator it = returnMap.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            System.out.println(pair.getKey() + " = " + pair.getValue());
            it.remove(); // avoids a ConcurrentModificationException
        }
        */
        System.out.println(returnMap);
        possibleActions.putAll(returnMap);
        return this;
    }


    /////////////////////////////////////// PRIVATE: ONLY USED BY FRAMEWORK /////////////////////////////////////////////////


}
