package CSGFramework.Website;

import java.util.ArrayList;
import java.util.List;

public class WebsiteBuilder {
    private String name = "mywebsite.com";
    private Webpage homeWebpage = new WebpageBuilder().setUrl(name).build();
    private List<Webpage> allWebpages = new ArrayList<>(){{add(homeWebpage);}};


    public Website build(){
        Website website = new Website(name, homeWebpage, allWebpages);
        for (Webpage webpage:allWebpages) {
            webpage.setWebsite(website);
        }
        generateRedirectingActions(3);
        return website;
    }

    public WebsiteBuilder setName(String name) {
        this.name = name;
        return this;
    }

    public WebsiteBuilder setHomeWebpage(Webpage homeWebpage) {
        this.homeWebpage = homeWebpage;
        return this;
    }

    public WebsiteBuilder addPages(List<Webpage> allWebpages) {
        this.allWebpages.addAll(allWebpages);
        return this;
    }

    public WebsiteBuilder addPage(Webpage webpage) {
        this.allWebpages.add(webpage);

        return this;
    }


    public WebsiteBuilder generateRedirectingActions(int numberOfRedirectingActions){
        //HashMap<Action, Webpage> returnMap = new HashMap<>();
        for(int i = 0; i < numberOfRedirectingActions; i++){
            System.out.println(i);
            Action action = new ActionBuilder().build();
            Webpage webpage = new WebpageBuilder().setUrl("randompage" + i + ".com").setNumberOfAutogeneratedActions(2).build();
            homeWebpage.addRedirectingAction(action,webpage);
            allWebpages.add(webpage);
        }
        return this;
    }






}
